# Generated by Django 6.0.1 on 2026-01-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_customerform_customer_email_and_more'),
        ('Products', '0006_cart_items'),
        ('groups', '0009_remove_order_items_approved_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='shg_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.shg_group_registration'),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.customerform'),
        ),
    ]
