# Generated by Django 5.2.7 on 2025-10-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shg_Group_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_sng', models.CharField(max_length=50)),
                ('date_of_formation', models.CharField()),
                ('registration_number', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=10)),
                ('village', models.CharField(max_length=15)),
                ('taluka', models.CharField(max_length=15)),
                ('district', models.CharField(blank=True, max_length=15, null=True)),
                ('type_of_shg', models.CharField(blank=True, max_length=10, null=True)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
    ]
