# Generated by Django 5.2.7 on 2025-10-28 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_customerform_alter_customer_orders_customer_id'),
        ('groups', '0004_rename_name_of_sng_shg_group_registration_name_of_shg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.customerform'),
        ),
    ]
