# Generated by Django 6.0.1 on 2026-01-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_shg_group_registration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='approved_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_items',
            name='delivered_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_items',
            name='rejected_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_items',
            name='shipped_order',
            field=models.BooleanField(default=False),
        ),
    ]
