# Generated by Django 6.0.1 on 2026-01-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_order_items_approved_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='approved_order',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='rejected_order',
        ),
        migrations.AddField(
            model_name='order_items',
            name='action',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10, null=True),
        ),
    ]
