# Generated by Django 5.2.7 on 2026-02-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_remove_order_items_approved_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shg_group_registration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images/'),
        ),
    ]
