# Generated by Django 5.2.7 on 2025-10-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_customerform_alter_customer_orders_customer_id'),
        ('groups', '0005_alter_order_items_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
