# Generated by Django 5.2 on 2026-01-17 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_remove_customerform_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerform',
            name='customer_email',
            field=models.EmailField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_orders',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customers.customerform'),
        ),
    ]
